"use client";

import { cn } from "@/lib/utils";
import { Check } from "lucide-react";
import Image from "next/image";

interface Props {
  value: number;
  onChange: (id: number) => void;
}

// Add new template options here as they are created.
// Thumbnail PNGs are generated by `make api-thumbs` (services/api/cmd/thumbgen).
const TEMPLATES = [
  { id: 1, label: "Classic", thumbnail: "/templates/classic.png" },
  { id: 2, label: "Modern", thumbnail: "/templates/modern.png" },
] as const;

export default function TemplateSelector({ value, onChange }: Props) {
  return (
    <div className="grid grid-cols-2 gap-3">
      {TEMPLATES.map((t) => {
        const selected = t.id === value;
        return (
          <button
            key={t.id}
            type="button"
            onClick={() => onChange(t.id)}
            className={cn(
              "group relative flex flex-col items-center gap-2 rounded-lg border-2 p-2 transition-colors hover:border-primary/60",
              selected
                ? "border-primary bg-primary/5"
                : "border-muted bg-background",
            )}
          >
            {/* Thumbnail */}
            <div className="relative aspect-[794/1123] w-full overflow-hidden rounded-md bg-muted">
              <Image
                src={t.thumbnail}
                alt={`${t.label} template preview`}
                fill
                className="object-cover object-top"
                sizes="160px"
              />
            </div>

            {/* Label + check */}
            <span className="flex items-center gap-1.5 text-xs font-medium">
              {selected && <Check className="h-3.5 w-3.5 text-primary" />}
              {t.label}
            </span>
          </button>
        );
      })}
    </div>
  );
}
